### ISSUE TITLE
Cant craft backpack/lookup the how to do it with JEI

### ISSUE THREAD

**Issue by justskrill** [Tiviacz1337/Travelers-Backpack#1401]
0. ALWAYS PROVIDE INFORMATION ABOUT MODLOADER (Fabric / Forge) AND MOD VERSION (For Example 1.19.2-8.2.10)

I'm using Fabric 0.18.1 with game version 1.21.10 

1. Describe the bug 

Tried crafting a basic backpack, didnt work, Cant even look up the recipes with JEI but non work

2. Write steps to reproduce the bug

Me wanting backpack - Trying to craft - Backpack no craft :(

3. What is expected behaviour 

To get a backpack crafted

4. Screenshots (If applicable)

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/494b5c78-e58e-4761-895d-fdeb87d80c67" />

**Comment by Na0k0z** [comment]
Hi,

I'm unsure if the crafting recipe you're showing is correct, however I can confirm on all versions of JEI, Traveler's Backpack doesn't display the Traveler's Backpack crafting. I tested this with the previous 1.21.10 Traveler's Backpack version, however it hasn't changed.

**Comment by justskrill** [comment]
> Hi,
> 
> I'm unsure if the crafting recipe you're showing is correct, however I can confirm on all versions of JEI, Traveler's Backpack doesn't display the Traveler's Backpack crafting. I tested this with the previous 1.21.10 Traveler's Backpack version, however it hasn't changed.

I googled the recipe and it was like it in my shown picture

**Comment by 703337** [comment]
Try string in place of the gold ingot.

**Comment by Tiviacz1337** [comment]
https://github.com/mezz/JustEnoughItems/issues/4208

**Comment by Tiviacz1337** [comment]
https://www.curseforge.com/minecraft/mc-mods/travelers-backpack-fabric

Fixed in 10.10.2

**Comment by sharky98** [comment]
Hi, I was wondering if all 10.10.2 has the bug fixed, or only in 1.21.11? I'm using `travelersbackpack-fabric-1.21.10-10.10.2.jar` on the server, same on client with Fabric `0.18.1` in Minecraft `1.21.10` and the recipes still doesn't show up in JEI for all Tier upgrades, and for all Backpack variation, including the base one. The only exception is the Netherite Tier and Netherite Backpack variation that does show (I suspect it is because they are done in the Smithing Table and not the Crafting Table).

EDIT: After upgrading to Minecraft `1.21.11` and Fabric `0.18.4`, I can say the recipes are showing in JEI in singleplayer, but not in multiplayer.

**Comment by Tiviacz1337** [comment]
> Hi, I was wondering if all 10.10.2 has the bug fixed, or only in 1.21.11? I'm using `travelersbackpack-fabric-1.21.10-10.10.2.jar` on the server, same on client with Fabric `0.18.1` in Minecraft `1.21.10` and the recipes still doesn't show up in JEI for all Tier upgrades, and for all Backpack variation, including the base one. The only exception is the Netherite Tier and Netherite Backpack variation that does show (I suspect it is because they are done in the Smithing Table and not the Crafting Table).
> 
> EDIT: After upgrading to Minecraft `1.21.11` and Fabric `0.18.4`, I can say the recipes are showing in JEI in singleplayer, but not in multiplayer.

Issue is fixed on 1.21.10 too, update JEI to latest for 1.21.10 and it should work fine
